// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UsernameForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><div id=\"blurScreen\" style=\"z-index: 250;\"></div><form id=\"sendUser\" hx-trigger=\"submit\" ws-send hx-on:submit=\"this.parentElement.remove()\"><input id=\"usernameInput\" name=\"username\" type=\"text\" placeholder=\"Username\" required><div id=\"userColorHolder\"><label>User Color:</label><div id=\"colorRadioHolder\"><input type=\"radio\" id=\"red\" class=\"colorRadio red\" name=\"radioColor\" value=\"red\" required> <input type=\"radio\" id=\"blue\" class=\"colorRadio blue\" name=\"radioColor\" value=\"blue\"> <input type=\"radio\" id=\"yellow\" class=\"colorRadio yellow\" name=\"radioColor\" value=\"yellow\"> <input type=\"radio\" id=\"green\" class=\"colorRadio green\" name=\"radioColor\" value=\"green\"> <input type=\"radio\" id=\"pink\" class=\"colorRadio pink\" name=\"radioColor\" value=\"pink\"> <input type=\"radio\" id=\"salmon\" class=\"colorRadio salmon\" name=\"radioColor\" value=\"salmon\"></div></div><button type=\"submit\">Join Room </button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
